<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div-ets-82c-944</name>
   <tag></tag>
   <elementGuidId>67b411c0-463c-4e6b-823f-5cfdd2f7fdad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nextjs-portal > div > div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97de3978-8aff-4607-81a0-397b25c4563b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nextjs-dialog-backdrop</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5d45f03-9515-4746-9e55-eb8172cc6f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[1]</value>
      <webElementGuid>7a67952e-8829-4b10-b8a5-387205793789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login_Obj/Page_5Pets/nextjs-portal-e_5Pets-82c</value>
      <webElementGuid>e2699de5-f808-4d14-9e08-c073cc881028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e003286e-19b9-41b7-a560-22d7ebd32297</webElementGuid>
   </webElementProperties>
</WebElementEntity>
