<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu_rememberLogin</name>
   <tag></tag>
   <elementGuidId>560dfec0-df93-489a-84f9-e1ca04242209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ghi nhớ đăng nhập&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6945b663-d4fc-43fc-ad94-31f761e60c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberLogin</value>
      <webElementGuid>fe60ff03-2759-4b38-8112-060d0b44455c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 accent-[#2B3674]</value>
      <webElementGuid>3f3c57de-fbcc-4b38-be8a-c04241234dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>188434f6-a010-4c75-8a89-3b075ccde9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberLogin</value>
      <webElementGuid>342a4257-9bbd-4bfb-9c62-9ca4e39a4eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberLogin&quot;)</value>
      <webElementGuid>d32b1dfb-0790-4b01-9160-e420fec4cfa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberLogin']</value>
      <webElementGuid>d43a6dd0-cbe4-4154-a633-6926d8969e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminLoginForm']/div[3]/div/input</value>
      <webElementGuid>29e61346-eb35-4372-9c45-0cf1af27526c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>d10d8311-8f5a-49b5-b1a3-4a6b5b391811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rememberLogin' and @type = 'checkbox' and @name = 'rememberLogin']</value>
      <webElementGuid>fbdaa871-2359-4a5c-adf5-b2ce70de462d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
