<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextjs-portal-e_5Pets-82c</name>
   <tag></tag>
   <elementGuidId>2ad2495b-5f7e-4829-b1c7-dd08266be340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nextjs-portal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nextjs-portal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nextjs-portal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nextjs-portal</value>
      <webElementGuid>36a34151-976d-4637-8bbc-172f6a071ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/script[21]/nextjs-portal[1]</value>
      <webElementGuid>b6c4ada3-0ad7-43d3-97be-55c2b268838f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nextjs-portal</value>
      <webElementGuid>e81852ad-fb49-4361-9796-c63d6a27fd7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
