<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Issues-ets-82c-ba7</name>
   <tag></tag>
   <elementGuidId>18089db1-06f0-4b2f-af82-65cec054ae52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel-route > #nextjs-dev-tools-menu > div > div.dev-tools-indicator-item > span.dev-tools-indicator-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nextjs-dev-tools-menu']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Issues&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f0219efe-b56d-4326-b0b0-855a01934905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dev-tools-indicator-label</value>
      <webElementGuid>fb1b63fb-cf62-4ef5-974a-d690625cda68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Issues</value>
      <webElementGuid>79f0736d-81f0-425b-83ca-53a73b6bf340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;panel-route&quot;]/div[@id=&quot;nextjs-dev-tools-menu&quot;]/div[1]/div[@class=&quot;dev-tools-indicator-item&quot;]/span[@class=&quot;dev-tools-indicator-label&quot;]</value>
      <webElementGuid>bb604274-4626-4405-864f-e6a80de4dde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login_Obj/Page_5Pets/nextjs-portal-e_5Pets-82c</value>
      <webElementGuid>6ac194b2-e4f4-46cf-9752-d9c53f327b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34af99a4-8733-415a-bd39-c5a62af88404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nextjs-dev-tools-menu']/div/div/span</value>
      <webElementGuid>cfa83689-72b9-4f81-b0eb-ff07679c1b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Issues']/parent::*</value>
      <webElementGuid>f66ece5a-7d2d-4939-941a-3188345e554b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Issues' or . = 'Issues')]</value>
      <webElementGuid>b64adedd-3d3d-489d-ad11-716fb32cb314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
