<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg-ets-82c-eea</name>
   <tag></tag>
   <elementGuidId>39546794-7982-44e8-ad9b-d53573f98c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#devtools-indicator > div > div > div > div > #next-logo > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next-logo']/svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open Next.js Dev Tools&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>bee77f91-6085-4fb0-8f0a-fddd981a45f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f1eb08b9-4315-4899-828c-38407f8f7402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>5f25f83f-c9af-4c67-a135-10b8e36cc48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 40 40</value>
      <webElementGuid>ba593c49-3024-4e31-8202-e34049e2b933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>dc480223-f5ad-4e6f-a335-3ce608686252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;devtools-indicator&quot;]/div[1]/div[1]/div[1]/div[1]/button[@id=&quot;next-logo&quot;]/svg[1]</value>
      <webElementGuid>32d1adb1-a7f6-423e-a49e-35e492f62090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login_Obj/Page_5Pets/nextjs-portal-e_5Pets-82c</value>
      <webElementGuid>e8bd5f7e-1e0a-4158-8e68-d34dda709189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e60fd75-ceaa-45fe-8887-6ec60cedac4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='next-logo']/svg</value>
      <webElementGuid>0920b09d-efcb-467d-b76d-e111a65b9ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>f89d499c-f4f4-4c15-8940-174767497c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
