<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mo</name>
   <tag></tag>
   <elementGuidId>01e2cb35-fe05-45b6-b14d-e6d60702dfb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-_R_kl9ev9etb_-trigger-radix-_r_1_']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mèo&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52ad35d0-5e05-467f-888f-bc11659c762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>navigation-menu-link</value>
      <webElementGuid>e9d5fe6f-33b8-4f14-913b-03d08d0a08bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col gap-1 rounded-sm p-2 transition-all outline-none hover:bg-accent focus:bg-accent focus:text-accent-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 data-[active]:bg-accent data-[active]:text-accent-foreground data-[active]:hover:bg-accent data-[active]:focus:bg-accent [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg:not([class*='text-'])]:text-muted-foreground text-[16px] font-bold text-[var(--main-color)]</value>
      <webElementGuid>b29d3f72-77d4-4bb0-9ff7-ef3d6ac79cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category/692b00818b153579ab1b5bf2</value>
      <webElementGuid>7b39db47-6894-43f5-b974-2823e6cff3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mèo</value>
      <webElementGuid>62bd622e-9fed-46c9-95db-0d76d96d06d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_R_kl9ev9etb_-trigger-radix-_r_1_&quot;)/a[@class=&quot;flex flex-col gap-1 rounded-sm p-2 transition-all outline-none hover:bg-accent focus:bg-accent focus:text-accent-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 data-[active]:bg-accent data-[active]:text-accent-foreground data-[active]:hover:bg-accent data-[active]:focus:bg-accent [&amp;_svg:not([class*='size-'])]:size-4 [&amp;_svg:not([class*='text-'])]:text-muted-foreground text-[16px] font-bold text-[var(--main-color)]&quot;]</value>
      <webElementGuid>539b9e2a-2ae6-4979-8bd5-1f683f8944d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='radix-_R_kl9ev9etb_-trigger-radix-_r_1_']/a</value>
      <webElementGuid>662b0d70-6d53-4e60-bbda-b00bd70c0cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mèo')]</value>
      <webElementGuid>b1c27d37-9ac4-43a5-a43e-f768e73922f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thỏ'])[1]/following::a[1]</value>
      <webElementGuid>960eb42f-3c7e-4507-865d-e8d4c4f1e712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::a[2]</value>
      <webElementGuid>c1e49e26-76fd-47ce-a022-e9f11e921ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mèo Mỹ Lông Ngắn'])[1]/preceding::a[1]</value>
      <webElementGuid>306e6000-80b1-433f-a6e8-61236c8173c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mèo Himalaya'])[1]/preceding::a[2]</value>
      <webElementGuid>39a19e41-36ab-481b-85ff-b609963df842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mèo']/parent::*</value>
      <webElementGuid>916e1004-1e75-4349-b565-30e379161223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/category/692b00818b153579ab1b5bf2')]</value>
      <webElementGuid>709b8c20-935e-4b45-b8f4-413fa3ac11b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/a</value>
      <webElementGuid>8c919cf5-43ca-4658-b978-9423d21d840a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/category/692b00818b153579ab1b5bf2' and (text() = 'Mèo' or . = 'Mèo')]</value>
      <webElementGuid>9b30ceab-6acd-42d7-9c5e-bb2735aa8943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
